apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: super-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: super-app
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s