apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-secret
  template:
    metadata:
      labels:
        app: flask-secret
    spec:
      containers:
        - name: flask-secret-container
          image: flask-configmap-app
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: secret-volume
              mountPath: /secret
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: flask-secret



from flask import Flask

app = Flask(__name__)

def get_secret_port():
    with open("/secret/FLASK_SECRET_PORT") as f:
        return int(f.read().strip())

@app.route("/")
def hello():
    port = get_secret_port()
    return f"Hello from Flask reading secret port {port}"

if __name__ == "__main__":
    port = get_secret_port()
    app.run(host="0.0.0.0", port=port)
