apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-container
          image: flask-configmap-app
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_PORT
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: FLASK_PORT
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: flask-config
