apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restart-alert
  labels:
    release: monitoring-kube-prometheus  # ce label est crucial !
spec:
  groups:
    - name: pod-restarts
      rules:
        - alert: PodCrashLoop
          expr: increase(kube_pod_container_status_restarts_total[5m]) > 2
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Crash détecté sur le pod"
            description: "Le pod a redémarré plus de 2 fois dans les 5 dernières minutes."
