apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: flask-metrics:v1
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /metrics
            port: 5000