apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flask
  endpoints:
    - port: "metrics"      # 👈 correspond au nom défini dans le service
      path: /metrics
      interval: 15s
