apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask   # important : ce label est utilisé par le ServiceMonitor
spec:
  selector:
    app: flask
  ports:
    - name: metrics        # 👈 OBLIGATOIRE pour ServiceMonitor
      port: 80
      targetPort: 5000
  type: ClusterIP
